- name: Create a data container
  community.docker.docker_container:
    name: "{{ item }}"
    image: docker.io/chaitu1812/git-image
    recreate: true
    pull: true
    restart: true
    env:
      TOKEN: "{{ TOKEN }}"
      NAME: "{{ item }}"
  loop:
    - runner-1
    - runner-2

