- name: Create a data container
  community.docker.docker_container:
    name: "{{ item }}"
    image: docker.io/chaitu1812/git-image
    pull: always
    restart: true
  loop:
    - runner-1
    - runner-2

