groups:
  - name: NodeUPAlerts
    rules:
      - alert: up
        expr: up < 1
        for: 1m
        labels:
          severity: CRITICAL
        annotations:
          summary: Node Down Alert

      - alert: upp
        expr: up < 1
        for: 1m
        labels:
          severity: sample
        annotations:
          summary: Node Down Alert