- name: alert
  ansible.builtin.systemd_service:
    name: alertmanager
    state: restarted
    enabled: yes
    daemon-reload: yes

- name: Prometheus
  ansible.builtin.systemd_service:
    name: prometheus
    state: restarted
    enabled: yes
    daemon-reload: yes