- name: Set Name in Prompt
  ansible.builtin.shell: set-hostname prometheus

- name: Download Prometheus
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v2.53.4/prometheus-2.53.4.linux-amd64.tar.gz
    dest: /opt
    remote_src: yes
    owner: bin
    creates: /opt/prometheus-2.53.4.linux-amd64

- name: Copy Prometheus Service File
  ansible.builtin.template:
    src: prometheus.service
    dest: /etc/systemd/system/prometheus.service

- name: Copy Promtheus Configuration
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus-2.53.4.linux-amd64/prometheus.yml


- name: Update Alerts
  ansible.builtin.template:
    src: alerts_rules.yml
    dest: /opt/prometheus-2.53.4.linux-amd64/alerts_rules.yml
    owner: bin
    group: bin

- name: Start Prometheus Service
  ansible.builtin.systemd_service:
    name: prometheus
    state: restarted
    enabled: yes
    daemon-reload: yes